### ISSUE TITLE
will you release the training code?

### ISSUE THREAD

**Issue by hollow-503** [pkyong95/PCVOS#2]
Thanks to your contribution on VOS! And i'm curious about whether you will release the training code because i want to train it on my  own dataset. Is it the same as STCN？

**Comment by netzahdzc** [comment]
Have you had access to the source code @hollow-503 ? Have you contacted the author?

**Comment by hollow-503** [comment]
> Have you had access to the source code @hollow-503 ? Have you contacted the author?

Sorry, the author did not reply me, and I did not get the source code.

**Comment by netzahdzc** [comment]
> > Have you had access to the source code @hollow-503 ? Have you contacted the author?
> 
> Sorry, the author did not reply me, and I did not get the source code.

That's unfortunate. Thank you for getting back to me.
